# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /usr/src/app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Run
FROM node:20-alpine
WORKDIR /usr/src/app

ENV NODE_ENV=production
# optional: ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /usr/src/app ./

# install only prod deps
RUN npm ci --omit=dev

EXPOSE 3000
CMD ["npm", "start"]