services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      caddy_net:
        aliases:
          - backend-prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    volumes:
      - ./frontend:/app
      - node_modules_dev:/app/node_modules
    networks:
      caddy_net:
        aliases:
          - frontend-prod

  postgres:
    image: postgres:14
    container_name: postgres-dev
    env_file:
      - ../dashboard/backend/.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - caddy_net

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - caddy_net

  caddy:
    image: caddy:2
    container_name: caddy-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_dev:/data
      - caddy_config_dev:/config
    networks:
      - caddy_net

volumes:
  postgres_data_dev:
  node_modules_dev:
  caddy_data_dev:
  caddy_config_dev:

networks:
  caddy_net: