services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    container_name: postgres-prod
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-prod
    ports:
      - "6379:6379"

  caddy:
    image: caddy:2
    container_name: caddy-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data_prod:/data
      - caddy_config_prod:/config

volumes:
  postgres_data_prod:
  caddy_data_prod:
  caddy_config_prod: