services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_dev:/app/node_modules

  postgres:
    image: postgres:14
    container_name: postgres-dev
    env_file:
      - ../dashboard/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"

  caddy:
    image: caddy:2
    container_name: caddy-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data_dev:/data
      - caddy_config_dev:/config

volumes:
  postgres_data_dev:
  node_modules_dev:
  caddy_data_dev:
  caddy_config_dev: